#!/bin/bash
# See http://askubuntu.com/questions/1792/how-can-i-suspend-hibernate-from-command-line/131022#131022
# See http://askubuntu.com/questions/777178/suspend-command-in-ubuntu-16-04

~/.i3/lock
systemctl suspend

